name: test

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Go
        uses: actions/setup-go@v2.1.5
        with:
          go-version: 1.13.x
      - run: make test
  acctest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Go
        uses: actions/setup-go@v2.1.5
        with:
          go-version: 1.13.x
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go
      - name: Bring up kafka + zk
        run: docker-compose up -d
      - name: "Run tests"
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin # temporary fix. See https://github.com/actions/setup-go/issues/14
          go install github.com/jstemmer/go-junit-report
          trap "go-junit-report < go-test.out > go-test-report.xml" EXIT
          make testacc | tee go-test.out
      - name: Upload test results
        uses: actions/upload-artifact@v1
        with:
          name: acc-test-results.xml
          path: go-test-report.xml
        # Use always() to always run this step to publish test results when there are test failures
        if: always()
